import {appBase} from './connection';
import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,NavLink,Navigate,Outlet,Link,useNavigate} from 'react-router-dom';
import {Activity,LayoutDashboard,Dumbbell,History,TrendingUp,Users,ChartNoAxesCombined,LogOut,Menu,ArrowRight,ShieldCheck,Check} from 'lucide-react';
import {AuthProvider,useAuth} from './auth';
import {api} from './api';
import {ServerSettings} from './ServerSettings';
import {ServerPage} from './ServerPage';
import {Field,ErrorMessage} from './ui';
import {Dashboard,Routines,RoutineDetail,Session,HistoryPage,Progress,Exercises,Athletes,AdminUsers,AdminReports,SharePage,Settings} from './pages';
import './style.css';
import '@fontsource/barlow-condensed/600.css';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
const roles={ATHLETE:'Atleta',TRAINER:'Entrenador',ADMIN:'Administrador'};
function Guard({allowed}){const {user,loading}=useAuth();if(loading)return <div className="loading">Preparando tu espacio…</div>;if(!user)return <Navigate to="/login" replace/>;if(allowed&&!allowed.includes(user.role))return <Navigate to="/" replace/>;return <Outlet/>;}
function Shell(){const {user,logout}=useAuth(),[open,setOpen]=useState(false);const links=[['/','Inicio',LayoutDashboard],['/routines','Rutinas',Dumbbell],['/history','Historial',History],['/progress','Progreso',TrendingUp],['/exercises','Ejercicios',Activity],...(user.role!=='ATHLETE'?[['/trainer/athletes','Atletas',Users]]:[]),...(user.role==='ADMIN'?[['/admin/users','Usuarios',ShieldCheck],['/admin/reports','Reportes',ChartNoAxesCombined],['/admin/server','Servidor',Activity]]:[])];return <div className="app-shell"><aside className={`sidebar ${open?'open':''}`}><Link to="/" className="brand"><span className="brand-symbol"><Activity size={24}/></span>rutina<span>track</span><small>ENTRENÁ. REGISTRÁ. CRECÉ.</small></Link><div className="nav-label">TU ESPACIO</div><nav>{links.map(([to,text,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={19}/>{text}</NavLink>)}</nav><div className="sidebar-bottom"><div className="live-dot">Todo tu progreso, en un lugar.</div><Link to="/settings" className="profile"><span className="avatar">{user.name[0]}</span><span><b>{user.name}</b><small>{roles[user.role]}</small></span></Link><button className="logout" onClick={logout}><LogOut size={17}/> Cerrar sesión</button></div></aside>{open&&<button className="scrim" aria-label="Cerrar menú" onClick={()=>setOpen(false)}/>}<div className="main-shell"><div className="topbar"><button className="icon-button mobile-menu" aria-label="Abrir menú" onClick={()=>setOpen(!open)}><Menu/></button><span className="topbar-label">TU CONSTANCIA HACE LA DIFERENCIA</span><span className="topbar-date">{new Date().toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}</span><span className="role-pill">{roles[user.role]}</span></div><main><Outlet/></main><footer>RUTINATRACK <span>Un entrenamiento a la vez.</span></footer></div></div>;}
function Login({register=false}){const {user,login}=useAuth(),navigate=useNavigate(),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(user)return <Navigate to="/" replace/>;async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(register)await api.post('/api/auth/register',{name,email,password:pass});await login(email,pass);navigate('/');}catch(e){setError(e.message);}finally{setBusy(false);}}return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-symbol"><Activity/></span>rutina<span>track</span></div><div className="login-statement"><span className="eyebrow">CADA REPETICIÓN CUENTA</span><h1>Tu esfuerzo.<br/>Tus números.<br/><em>Tu progreso.</em></h1><p>El espacio donde tus entrenamientos se convierten en resultados que podés ver.</p><div className="sample-bars" aria-hidden="true">{[23,31,28,41,45,52,50,67,78,91,100].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><span className="small-label">LA CONSTANCIA SE CONSTRUYE, SERIE A SERIE.</span></div><span className="login-footer">HECHO PARA ENTRENAR MEJOR.</span></section><section className="login-form"><div className="login-box"><div className="login-tag"><span/> TU PRÓXIMO PASO EMPIEZA ACÁ</div><h2>{register?'Creá tu cuenta':'Qué bueno verte.'}</h2><p>{register?'Tu espacio de atleta, listo para empezar.':'Ingresá y seguí donde lo dejaste.'}</p><ServerSettings/><form onSubmit={submit}>{register&&<Field label="Nombre" value={name} onChange={e=>setName(e.target.value)} required autoComplete="name"/>}<Field label="Email" type="email" placeholder="tu@email.com" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/><Field label="Contraseña" type="password" placeholder="Tu contraseña" minLength={8} value={pass} onChange={e=>setPass(e.target.value)} required autoComplete={register?'new-password':'current-password'}/><ErrorMessage text={error}/><button className="primary full" disabled={busy}>{busy?'Conectando…':register?'Crear cuenta':'Iniciar sesión'}<ArrowRight size={18}/></button></form><p className="switch-auth">{register?'¿Ya tenés cuenta?':'¿Primera vez por acá?'} <Link to={register?'/login':'/register'}>{register?'Iniciá sesión':'Creá tu cuenta'}</Link></p>{import.meta.env.DEV&&<div className="demo-logins"><span className="small-label">PROBÁ LA DEMO</span><div>{[['Lucía','lucia','Lucia123!'],['Diego','diego','Diego123!'],['Entrenador','entrenador','Entrena123!'],['Admin','admin','Admin123!']].map(([label,email,password])=><button key={email} type="button" onClick={()=>{setEmail(email+'@demo.local');setPass(password);}}>{label}</button>)}</div><small>Elegí un perfil y presioná Iniciar sesión.</small></div>}<div className="login-note"><Check size={16}/> Rutinas, sesiones y progreso en un solo lugar.</div></div></section></div>;}
function App(){return <BrowserRouter basename={appBase||'/'}><AuthProvider><Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Login register/>}/><Route path="/s/:token" element={<SharePage/>}/><Route element={<Guard/>}><Route element={<Shell/>}><Route index element={<Dashboard/>}/><Route path="routines" element={<Routines/>}/><Route path="routines/:id" element={<RoutineDetail/>}/><Route path="session/:id" element={<Session/>}/><Route path="history" element={<HistoryPage/>}/><Route path="progress" element={<Progress/>}/><Route path="exercises" element={<Exercises/>}/><Route path="settings" element={<Settings/>}/><Route element={<Guard allowed={['TRAINER','ADMIN']}/>}><Route path="trainer/athletes" element={<Athletes/>}/></Route><Route element={<Guard allowed={['ADMIN']}/>}><Route path="admin/users" element={<AdminUsers/>}/><Route path="admin/reports" element={<AdminReports/>}/><Route path="admin/server" element={<ServerPage/>}/></Route></Route></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></AuthProvider></BrowserRouter>;}
createRoot(document.getElementById('root')).render(<App/>);


