import {useState} from 'react';
import {Copy,Check,Server,Globe,Wifi} from 'lucide-react';
import {get} from './api';
import {useLoad,Title,Panel,State,Stat,ErrorMessage} from './ui';
export function ServerPage(){
  const load=useLoad(()=>get('/api/server')),[copied,setCopied]=useState(''),[error,setError]=useState('');
  const copy=async value=>{try{await navigator.clipboard.writeText(value);setCopied(value);}catch{setError('No se pudo copiar automáticamente. Seleccioná la dirección para copiarla.');}};
  const d=load.data;
  return <><Title eyebrow="ADMINISTRACIÓN" title="Servidor y conexiones" subtitle="Un mismo gimnasio, conectado desde varios equipos." action={<button className="secondary" onClick={load.reload}>Actualizar estado</button>}/><State {...load}>{d&&<><div className="stats"><Stat label="ESTADO DEL SERVIDOR" value="Activo" note="Listo para recibir conexiones"/><Stat label="USUARIOS ACTIVOS" value={d.active_users} note="Cuentas habilitadas"/><Stat label="ENTRENAMIENTOS EN CURSO" value={d.in_progress_sessions} note="Sesiones abiertas"/></div><div className="two-columns"><Panel title="Conectar desde Internet" aside={<Globe size={21}/>} >{d.public_origin?<><p>Compartí esta dirección con tus atletas y entrenadores. Funciona con datos móviles y desde otras redes.</p><div className="server-address"><a href={d.public_origin} target="_blank" rel="noreferrer">{d.public_origin}</a><button className="icon-button" aria-label="Copiar dirección pública" onClick={()=>copy(d.public_origin)}>{copied===d.public_origin?<Check size={18}/>:<Copy size={18}/>}</button></div><p>En las apps, guardá esta dirección en Servidor e ingresá con tu cuenta.</p></>:<><p>El servidor público todavía no está configurado. Para conectar desde cualquier lugar, necesitás alojar el servidor central con una dirección HTTPS.</p><div className="instruction"><b>Una sola base para todo el equipo</b><p>Cuando esté publicado, conectá Windows, Android e iOS a la misma dirección. Las rutinas y los entrenamientos se guardarán juntos.</p></div></>}</Panel><Panel title="Conectar en la red del gimnasio" aside={<Wifi size={21}/>} >{d.public_origin?<p>Ya tenés una dirección pública. Usala también dentro del gimnasio.</p>:<><p>Conectá las computadoras al mismo Wi-Fi o red local y abrí una de estas direcciones en el navegador.</p>{d.local_origins.map(url=><div key={url} className="server-address"><a href={url} target="_blank" rel="noreferrer">{url}</a><button className="icon-button" aria-label={`Copiar ${url}`} onClick={()=>copy(url)}>{copied===url?<Check size={18}/>:<Copy size={18}/>}</button></div>)}{!d.local_origins.length&&<p>No se detectó una dirección de red local.</p>}<small>El firewall de esta PC debe permitir conexiones al puerto {d.port} en la red privada.</small></>}</Panel></div><Panel title={d.mode==='desktop'?'Esta PC es el servidor':'Servidor central en funcionamiento'} aside={<Server size={21}/>}><p>{d.mode==='desktop'?'Podés cerrar la ventana: RutinaTrack seguirá atendiendo a los otros equipos desde la bandeja del sistema. Para apagarlo, elegí Salir y apagar servidor en el ícono junto al reloj. La PC debe permanecer encendida y sin suspender.':'Los demás equipos usan sus propias cuentas y trabajan sobre la misma base del servidor. Cada atleta y entrenador conserva sus permisos.'}</p><p className="muted">No hay sincronización automática entre una base local y otra remota. Para compartir los datos, todos deben conectarse al mismo servidor.</p></Panel></>}</State><ErrorMessage text={error}/></>;
}
